# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Data Management'
tagline:             'a companion'
description: > # This is the companion website for Data and Database Management course in McGill University, Desautels Faculty of Management.
baseurl:             '/data-management'
url:                 'http://retrography.github.com/data-management'
paginate:            5

# About/contact
author:
  name:              'Mahmood Zargar'
  url:               'https://twitter.com/mszargar'
  email:             'mahmood.shafeiezargar@mcgill.ca'

# Custom vars
version:             1.0.0
